### ISSUE TITLE
DeltaTable.create raises aws region errors with moto

### ISSUE THREAD

**Issue by jensqin** [delta-io/delta-rs#3111]
# Environment

**Delta-rs version**: 0.23.2

**Binding**: 0.23.2

**Environment**:
- **Cloud provider**: moto
- **OS**: macOS
- **Other**:

***
# Bug

**What happened**: DeltaTable.create raises aws region errors with moto

```python
[undefined]OSError: Generic S3 error: Error performing list request: Received redirect without LOCATION, this normally indicates an incorrectly configured region
```

**What you expected to happen**: successful run with no errors

**How to reproduce it**:

```python
import boto3
import pytest
from deltalake import DeltaTable, Field, Schema
from moto import mock_aws


def test_deltalake():
    with mock_aws():
        conn = boto3.resource("s3", region_name="us-east-1")
        conn.create_bucket(Bucket="mybucket")

        bucket = S3Bucket("mybucket", "us-east-1")
        bucket.save_object("hello", "world")

        body = conn.Object("mybucket", "hello").get()["Body"].read()
        assert body == b"world"

        schema = Schema([Field("x", "integer"), Field("y", "integer")])

        storage_options = {"AWS_REGION": "us-east-1"}
        dt = DeltaTable.create(
            "s3://mybucket/test", schema, storage_options=storage_options
        )
        dt = DeltaTable("s3://mybucket/test", storage_options=storage_options)
        assert dt is not None
```

**More details**:

**Comment by ion-elgreco** [comment]
@jensqin have you tried with "aws_region"?

This issue might already been fixed in main since this PR: https://github.com/delta-io/delta-rs/pull/3107

**Comment by DanJourno** [comment]
I still have the same error with AWS as a cloud provider and this environment 
# Environment

Delta-rs version: 0.24.0

Binding: 0.24.0

Environment:

Cloud provider: AWS
OS: macOS
Other:

**Comment by jensqin** [comment]
@ion-elgreco This issue has been fixed with 0.24.0, thanks for your great work!

**Comment by phildong** [comment]
sorry for the potential spam, but the same issue seem to resurfaced:

deltalake version: 1.1.4
moto version: 5.1.11
os: Ubuntu 22.04.5
