### ISSUE TITLE
[Bug]: `deltalake.DeltaTable.is_deltatable` can hang under certain conditions

### ISSUE THREAD

**Issue by danielgafni** [delta-io/delta-rs#3942]
### What happened?

We've ran into [issues](https://github.com/anam-org/metaxy/pull/314) when running integration tests against [moto.ThreadedMotoServer](https://docs.getmoto.org/en/latest/docs/server_mode.html). 

Somehow `deltalake.DeltaTable.is_deltatable` call -- and also `polars.scan_delta` which might be calling it under the hood -- hangs against a `moto` S3 server running in the same Python process. This may have something to do with GIL or not, I am really not sure, it's strange, because it's supposed to release the GIL anyway, right? 

Doing `deltalake.DeltaTable(..., without_files=True)` with the same URI works just fine. Only `is_deltatable` is causing the hang.  

### Expected behavior

It should not hang 🤷‍♂️ ?

### Operating System

None

### Binding

None

### Steps to reproduce

There is a reproducible example [here](https://github.com/anam-org/metaxy/pull/313/commits/b645a27229388930d9b4bd5ffa0f12d37525d9ae#diff-d4582ad006ab6b322e5b4136fc58f2fa997a97aa0186d29d4a466573e0a49d74R51). 

The test can be invoked with: 

```shell
$ uv run pytest tests/metadata_stores/test_delta.py::test_delta_hanging
```

### Relevant logs

```shell

```

**Comment by danielgafni** [comment]
@ion-elgreco @geoHeil cc

**Comment by vsmanish1772** [comment]
Could this be related? https://github.com/delta-io/delta-kernel-rs/issues/1410 I have been having issues with mocking few delta operations since I moved to 1.2.1 
Not all operations fail but few does. In my case calling transaction_version() gets stuck and fails eventually with timeout

**Comment by rtyler** [comment]
There were a couple issues that I think were fixed in the latest release of kernel, so once #3949 has been merged this should be tried again

**Comment by mivade** [comment]
Looks like that was merged. Will there be a new release on PyPI soon?

**Comment by rtyler** [comment]
1.3.0 was released, I believe is fixed, please re-open if that's not the case!

**Comment by mivade** [comment]
So far in my use case I haven't seen an improvement. I'll try to investigate further and see if there is something wrong on my end or not.

**Comment by danielgafni** [comment]
The issue remains for us as well. Your fix didn't resolve it for us. 

P.S. I don't have permissions to reopen this issue.

**Comment by mivade** [comment]
I cannot reopen it either.

**Comment by khalidmammadov** [comment]
@danielgafni can you please repost reproducable example? it's not available anymore.

**Comment by danielgafni** [comment]
@khalidmammadov https://github.com/anam-org/metaxy/pull/953

**Comment by rtyler** [comment]
@danielgafni I looked at the related code and I'm not seeing what might cause the issue, since it looks like in that code just claling is_deltatable causes a hang? If that's the case, when I would be curious if this happens when there's another polars scan or something running behind the scenes.

Essentially I'm guessing that maybe there's something underneath the covers here where delta-rs and polars are both making assumptions about the default tokio runtime which are not correct 🤔

**Comment by rtyler** [comment]
I believe I have fixed what I _think_ is the culprit here with some changes in `buoyant_kernel`. I'm going to close this
